version: '3'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "6001:6001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/userDB

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "6002:6002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/productDB

  api-gateway:
    build: ./api-gateway
    ports:
      - "6600:6600"
    depends_on:
      - user-service
      - product-service

  mongo:
    image: mongo
    ports:
      - "27017:27017"